openstack_registry should run migrations

diff --git a/jobs/openstack_registry/templates/openstack_registry_ctl b/jobs/openstack_registry/templates/openstack_registry_ctl
--- a/jobs/openstack_registry/templates/openstack_registry_ctl
+++ b/jobs/openstack_registry/templates/openstack_registry_ctl
@@ -15,6 +15,16 @@ case $1 in
 
     echo $$ > $PIDFILE
 
+    chpst -u $RUNAS:$RUNAS \
+      /var/vcap/packages/openstack_registry/bosh/openstack_registry/bin/migrate \
+      -c /var/vcap/jobs/openstack_registry/config/openstack_registry.yml \
+      >>$LOG_DIR/migrate.stdout.log 2>>$LOG_DIR/migrate.stderr.log
+
+    if [ $? -ne 0 ]; then
+      echo "migration failed"
+      exit 1
+    fi
+
     exec chpst -u $RUNAS:$RUNAS \
       /var/vcap/packages/openstack_registry/bosh/openstack_registry/bin/openstack_registry \
       -c /var/vcap/jobs/openstack_registry/config/openstack_registry.yml \
